"""empty message

Revision ID: 209f05abe0b3
Revises: 67b69a3669bd
Create Date: 2021-10-29 09:42:36.731356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '209f05abe0b3'
down_revision = '67b69a3669bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists_genres', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('artists_genres', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('artists_genres_genre_id_fkey', 'artists_genres', type_='foreignkey')
    op.drop_constraint('artists_genres_artist_id_fkey', 'artists_genres', type_='foreignkey')
    op.create_foreign_key(None, 'artists_genres', 'Genre', ['genre_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'artists_genres', 'Artist', ['artist_id'], ['id'], ondelete='cascade')
    op.alter_column('artists_shows', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('artists_shows', 'show_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('artists_shows_artist_id_fkey', 'artists_shows', type_='foreignkey')
    op.drop_constraint('artists_shows_show_id_fkey', 'artists_shows', type_='foreignkey')
    op.create_foreign_key(None, 'artists_shows', 'Artist', ['artist_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'artists_shows', 'Show', ['show_id'], ['id'], ondelete='cascade')
    op.drop_constraint('venues_shows_shows_id_fkey', 'venues_shows', type_='foreignkey')
    op.drop_constraint('venues_shows_venues_id_fkey', 'venues_shows', type_='foreignkey')
    op.create_foreign_key(None, 'venues_shows', 'Venue', ['venues_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'venues_shows', 'Show', ['shows_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venues_shows', type_='foreignkey')
    op.drop_constraint(None, 'venues_shows', type_='foreignkey')
    op.create_foreign_key('venues_shows_venues_id_fkey', 'venues_shows', 'Venue', ['venues_id'], ['id'])
    op.create_foreign_key('venues_shows_shows_id_fkey', 'venues_shows', 'Show', ['shows_id'], ['id'])
    op.drop_constraint(None, 'artists_shows', type_='foreignkey')
    op.drop_constraint(None, 'artists_shows', type_='foreignkey')
    op.create_foreign_key('artists_shows_show_id_fkey', 'artists_shows', 'Show', ['show_id'], ['id'])
    op.create_foreign_key('artists_shows_artist_id_fkey', 'artists_shows', 'Artist', ['artist_id'], ['id'])
    op.alter_column('artists_shows', 'show_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('artists_shows', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'artists_genres', type_='foreignkey')
    op.drop_constraint(None, 'artists_genres', type_='foreignkey')
    op.create_foreign_key('artists_genres_artist_id_fkey', 'artists_genres', 'Artist', ['artist_id'], ['id'])
    op.create_foreign_key('artists_genres_genre_id_fkey', 'artists_genres', 'Genre', ['genre_id'], ['id'])
    op.alter_column('artists_genres', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('artists_genres', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
