"""empty message

Revision ID: 312e99aff60e
Revises: 29d922638fb9
Create Date: 2021-10-30 15:30:48.016864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312e99aff60e'
down_revision = '29d922638fb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.alter_column('Show', 'start_time', type_=sa.DateTime, existing_type=sa.String, postgresql_using='start_time::timestamp without time zone')
    op.alter_column('Show', 'start_time', type_=sa.DateTime(timezone=False), existing_type=sa.String, postgresql_using='start_time::timestamp without time zone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    #op.drop_column('Show', 'test_field')
    # ### end Alembic commands ###
