"""empty message

Revision ID: 860a0431689a
Revises: 209f05abe0b3
Create Date: 2021-10-29 16:11:17.038218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860a0431689a'
down_revision = '209f05abe0b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues_genres',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['Genre.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('venue_id', 'genre_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venues_genres')
    # ### end Alembic commands ###
